<?php

namespace App\Services\Reports;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Contracts\View\Factory as ViewFactory;
use Illuminate\Http\Response;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ReportExportService
{
    public function __construct(
        private readonly ViewFactory $views,
    ) {}

    public function csv(array $dataset, array $filters, string $generatedBy): StreamedResponse
    {
        $filename = str($dataset['title'])->slug('-')->append('.csv')->toString();

        return response()->streamDownload(function () use ($dataset, $filters, $generatedBy): void {
            $handle = fopen('php://output', 'wb');

            fputcsv($handle, ['Ysabelle Retail']);
            fputcsv($handle, [$dataset['title']]);
            fputcsv($handle, ['Generated Date', now()->format('Y-m-d H:i:s')]);
            fputcsv($handle, ['Generated By', $generatedBy]);
            fputcsv($handle, ['Date From', $filters['date_from'] ?? '']);
            fputcsv($handle, ['Date To', $filters['date_to'] ?? '']);
            fputcsv($handle, []);
            fputcsv($handle, $dataset['columns']);

            foreach ($dataset['rows'] as $row) {
                fputcsv($handle, $row);
            }

            fputcsv($handle, []);

            foreach ($dataset['totals'] as $label => $value) {
                fputcsv($handle, [str($label)->headline()->toString(), $value]);
            }

            fclose($handle);
        }, $filename, [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    public function pdf(array $dataset, array $filters, string $generatedBy): Response
    {
        $html = $this->views->make('admin.reports.pdf', [
            'dataset' => $dataset,
            'filters' => $filters,
            'generatedBy' => $generatedBy,
        ])->render();

        return Pdf::loadHTML($html)
            ->setPaper('a4', 'landscape')
            ->download(str($dataset['title'])->slug('-')->append('.pdf')->toString());
    }

    public function xlsx(array $dataset, array $filters, string $generatedBy): StreamedResponse
    {
        $filename = str($dataset['title'])->slug('-')->append('.xlsx')->toString();

        return response()->streamDownload(function () use ($dataset, $filters, $generatedBy): void {
            $spreadsheet = new Spreadsheet;
            $sheet = $spreadsheet->getActiveSheet();

            $rows = [
                ['Ysabelle Retail Shop'],
                [$dataset['title']],
                ['Generated Date', now()->format('Y-m-d H:i:s')],
                ['Generated By', $generatedBy],
                ['Date From', $filters['date_from'] ?? '-'],
                ['Date To', $filters['date_to'] ?? '-'],
                [],
                $dataset['columns'],
            ];

            foreach ($dataset['rows'] as $row) {
                $rows[] = $row;
            }

            $rows[] = [];

            foreach ($dataset['totals'] as $label => $value) {
                $rows[] = [str($label)->headline()->toString(), $value];
            }

            foreach ($rows as $rowIndex => $row) {
                $sheet->fromArray($row, null, 'A'.($rowIndex + 1), true);
            }

            foreach (range('A', $sheet->getHighestColumn()) as $column) {
                $sheet->getColumnDimension($column)->setAutoSize(true);
            }

            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
        }, $filename, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ]);
    }
}
