<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <style>
            body { font-family: DejaVu Sans, sans-serif; color: #181818; font-size: 12px; }
            h1 { margin: 0 0 6px; font-size: 22px; }
            p { margin: 0 0 4px; }
            .meta { margin-bottom: 18px; color: #555; }
            .brand { color: #9c7327; font-weight: bold; letter-spacing: 0.18em; text-transform: uppercase; font-size: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 18px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }
            th { background: #f5efe0; color: #7b5a1a; text-transform: uppercase; font-size: 10px; letter-spacing: 0.14em; }
            .totals { margin-top: 18px; }
        </style>
    </head>
    <body>
        <p class="brand">Ysabelle Retail</p>
        <h1>{{ $dataset['title'] }}</h1>
        <div class="meta">
            <p>Generated Date: {{ now()->format('Y-m-d H:i:s') }}</p>
            <p>Generated By: {{ $generatedBy }}</p>
            <p>Date Range: {{ $filters['date_from'] ?: '—' }} to {{ $filters['date_to'] ?: '—' }}</p>
        </div>

        <table>
            <thead>
                <tr>
                    @foreach ($dataset['columns'] as $column)
                        <th>{{ $column }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($dataset['rows'] as $row)
                    <tr>
                        @foreach ($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="totals">
            @foreach ($dataset['totals'] as $label => $value)
                <p><strong>{{ str($label)->headline() }}:</strong> {{ is_float($value) ? 'PHP '.number_format($value, 2) : $value }}</p>
            @endforeach
        </div>
    </body>
</html>
